#FOR DEPLOYMENT
spring.application.name=ai-agent
server.servlet.context-path=/api

## JWT
jwt.secretKey=
deploy.env=deployment
jwt.expiration=

#REDIS CONFIGURATIONS:
spring.data.redis.host=
spring.data.redis.port=
spring.data.redis.password=

#OPENAI CONFIG->
openai.api.key=
openai.base.url=

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.owner=Mr.Prateek Gupta
info.app.version=4.0.2
info.app.swagger=
info.app.api.docs=

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
logging.level.root=INFO



