logging:
  level:
    org.springframework.data.mongodb:
      core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb://admin:password@localhost:27017/aiagent?authSource=admin
    #run this in docker mongo comtainer's exec tab :
    #mongosh -u admin -p password -authenticationDatabase admin

  security.oauth2.client:
    provider:
      twitter:
        authorization-uri: https://twitter.com/i/oauth2/authorize
        token-uri: https://api.twitter.com/2/oauth2/token
        user-info-uri: https://api.twitter.com/2/users/me
        user-name-attribute: id

    registration:
      google:
        client-id: 1049671618334-qp1e569lk02u8n8u5ia40qjpe6gs0f00.apps.googleusercontent.com
        client-secret: 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
      github:
        client-id: Ov23liDNZOj6fRNAyIr7
        client-secret: 7348245f6010707b73a9242b1fff741cf7bfa953
      twitter:
        client-id: asdlfjasldf
        client-secret: asldfjalsdfj
        redirect-uri: "{baseUrl}/login/oauth2/code/twitter"
        authorization-grant-type: authorization_code
        scope:
          - tweet.read
          - users.read
          - offline.access
        client-name: Twitter
        provider: twitter