logging:
  level:
    org.springframework.data.mongodb:
      core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb://admin:password@localhost:27017/aiagent?authSource=admin

  security.oauth2.client:
    provider:
      twitter:
        authorization-uri: https://twitter.com/i/oauth2/authorize
        token-uri: https://api.twitter.com/2/oauth2/token
        user-info-uri: https://api.twitter.com/2/users/me
        user-name-attribute: id

    registration:
      google:
        client-id: 
        client-secret: 
      github:
        client-id: 
        client-secret: 
      twitter:
        client-id: 
        client-secret: 
        redirect-uri: "{baseUrl}/login/oauth2/code/twitter"
        authorization-grant-type: authorization_code
        scope:
          - tweet.read
          - users.read
          - offline.access
        client-name: Twitter
        provider: twitter
