#FOR DEPLOYMENT
spring.application.name=ai-agent
server.servlet.context-path=/api

## JWT
jwt.secretKey=
deploy.env=deployment

#REDIS CONFIGURATIONS:
spring.data.redis.host=petunia-uncluttered-chess-32220.db.redis.io
spring.data.redis.port=10056
spring.data.redis.password=am2qrU9kkC7sAv5F7zDbIChhu26WoVEt

#OPENAI CONFIG->
openai.api.key=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
openai.base.url=https://openrouter.ai/api/v1

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.owner=Mr.Prateek Gupta
info.app.version=5.0

info.app.swagger=
info.app.api.docs=

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

#LUCENE:
code-search.lucene.index-path=./data/lucene




