#openai.api.key=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
#setx OPENROUTER_API_KEY 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
#FOR DEPLOYMENT
spring.application.name=ai-agent
#openai.api.key=${OPENROUTER_API_KEY}
#openai.base.url=${OPENROUTER_BASE_URL:https://openrouter.ai/api/v1}
#set environment variable in cmd and start ide: setx OPENROUTER_API_KEY <your_real_key_here>
server.servlet.context-path=/api
openai.api.key=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
openai.base.url=https://openrouter.ai/api/v1
#SWAGGER: http://localhost:8080/api/swagger-ui/index.html
#http://localhost:8080/api/v3/api-docs
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.owner=Mr.Prateek Gupta
info.app.version=4.0
info.app.swagger=http://localhost:8080/api/swagger-ui/index.html
info.app.api.docs=http://localhost:8080/api/v3/api-docs
#spring.mongodb.uri=mongodb://localhost:27017/ai_agent_db
#spring.data.mongodb.uri=mongodb://localhost:27017/ai-agent-db

#These 2 will be fetched by InMemoryUserDetailsManager
#spring.security.user.name=admin
#spring.security.user.password=password
#logging.level.root = DEBUG
## MongoDB
#spring.data.mongodb.uri=mongodb://localhost:27017/ai-agent-db
#
## JWT
jwt.secretKey=jhasguydgsdud783y86543bhdhh73t9gvgy2387hubfd678dcdes35dv7v9dvghdhvd5d6c8dhvdghvf6
deploy.env=deployment
#jwt.expiration=86400000
#
## OAuth (optional for later)
#spring.security.oauth2.client.registration.google.client-id=YOUR_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_SECRET





#FROM: LearningRestApis
#
#spring.application.name=LearningRESTAPIs
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/studentsDB
#spring.datasource.username=postgres
#spring.datasource.password=admin
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.servlet.context-path=/api
